micronaut:
  application:
    name: fretesRest

grpc:
  client:
    plaintext: true
    max-retry-attempt: 10
  channels:
    fretes:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempt: 10
  server:
    health:
      enabled: true

endpoints:
  all:
    sensitive: false
  health:
    enable: true
    sensitive: false
    details-visible: ANONYMOUS
